name: build python
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - python/**
      - .github/workflows/python.yml
jobs:
  push:
    if: "${{((startsWith(github.event.head_commit.message, '[push]') || startsWith(github.event.head_commit.message, '[dev]') ) && github.event_name == 'push' ) || github.event_name == 'workflow_dispatch'}}"
    name: "yolks:python_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '3.6'
    steps:
      - uses: actions/checkout@v3
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./python
          file: ./python/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/thakyz/yolks:python_${{ matrix.tag }}
