name: build steamcmd
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
      - dev
    paths:
      - steamcmd/**
      - .github/workflows/steamcmd.yml
jobs:
  before_push:
    name: "steamcmd before push"
    runs-on: ubuntu-latest
    steps:
      - name: "test variables"
        shell: pwsh
        run: |
          $JsonTextZero = '${{ toJSON(github.event.commits) }}';
          $JsonTextAny = '${{ toJSON(github.event.commits) }}';
          $JsonZero = ($JsonTextZero | ConvertFrom-Json)
          $JsonAny = ($JsonTextAny | ConvertFrom-Json)
          Write-Output -InputObject $JsonZero | Out-Host;
          Write-Output -InputObject $JsonAny | Out-Host;
  push:
    if: ${{ ( ( startsWith(toJSON(github.event.commits.*.message), '[push]') || startsWith(toJSON(github.event.commits.*.message), '[dev]') ) && github.event_name == 'push' ) || github.event_name == 'workflow_dispatch' }}
    name: "steamcmd:${{ matrix.distro }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - proton
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./steamcmd
          file: ./steamcmd/${{ matrix.distro }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/thakyz/steamcmd:${{ matrix.distro }}
